# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oauth2c < Formula
  desc "CLI for OAuth2"
  homepage "https://github.com/cloudentity/oauth2c"
  version "1.10.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cloudentity/oauth2c/releases/download/v1.10.1/oauth2c_1.10.1_Darwin_arm64.tar.gz"
      sha256 "1a9cc15ef29364250920982b60b14215f8b52b4bde55ee9acb25a81292eefa5b"

      def install
        bin.install "oauth2c"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cloudentity/oauth2c/releases/download/v1.10.1/oauth2c_1.10.1_Darwin_x86_64.tar.gz"
      sha256 "73d3e0307e0df548c5ac7dca3ce7340a90685f102a4e2ad0865b0dafdb867e19"

      def install
        bin.install "oauth2c"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/cloudentity/oauth2c/releases/download/v1.10.1/oauth2c_1.10.1_Linux_arm.tar.gz"
      sha256 "6867f8b920459726e4b05ec0d805bcfe8dec671c8136a35240fbdd4e5568dfad"

      def install
        bin.install "oauth2c"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cloudentity/oauth2c/releases/download/v1.10.1/oauth2c_1.10.1_Linux_x86_64.tar.gz"
      sha256 "a29e67ff4f20d9e1523c858e1fb7e142e7285b07cde06774d26db55a61a4cd33"

      def install
        bin.install "oauth2c"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudentity/oauth2c/releases/download/v1.10.1/oauth2c_1.10.1_Linux_arm64.tar.gz"
      sha256 "d862687b054677efebb0cae02537a42bab691924bf876dab6b95c725a43a25bd"

      def install
        bin.install "oauth2c"
      end
    end
  end
end
