# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oauth2c < Formula
  desc "CLI for OAuth2"
  homepage "https://github.com/cloudentity/oauth2c"
  version "1.10.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cloudentity/oauth2c/releases/download/v1.10.0/oauth2c_1.10.0_Darwin_x86_64.tar.gz"
      sha256 "a898d64c964d78454859422e1366e0d3b973991cb95ef121f83761835ee89283"

      def install
        bin.install "oauth2c"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cloudentity/oauth2c/releases/download/v1.10.0/oauth2c_1.10.0_Darwin_arm64.tar.gz"
      sha256 "d042f7a6d175c905a02e78aa71d0f8042792ec64569e947e6cb11b3d2b4e51ca"

      def install
        bin.install "oauth2c"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/cloudentity/oauth2c/releases/download/v1.10.0/oauth2c_1.10.0_Linux_arm.tar.gz"
      sha256 "ddff3dcb15fc17bc72a2b7a603fca376af16a4b18d84805e59b5c46e8daaece2"

      def install
        bin.install "oauth2c"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cloudentity/oauth2c/releases/download/v1.10.0/oauth2c_1.10.0_Linux_x86_64.tar.gz"
      sha256 "091c4026f81f75628ac62e2e9efd5a5648952ce6add99253b861dc676735b974"

      def install
        bin.install "oauth2c"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudentity/oauth2c/releases/download/v1.10.0/oauth2c_1.10.0_Linux_arm64.tar.gz"
      sha256 "5d4dc212606bc7532b5e87c3df7116f82a79334caa5a3341c96be5c679bd1b71"

      def install
        bin.install "oauth2c"
      end
    end
  end
end
